version: '3.8'

services:
  api:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    container_name: forex_api
    ports:
      - ${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
  cache:
    image: redis:6.2
    container_name: forex_cache
    volumes:
      - redisdata:/var/lib/redis/data
    ports:
      - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 10s
      retries: 5
  db:
    image: postgres:12.7
    container_name: forex_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    healthcheck:
      test: pg_isready -q -d forex -U postgres
      interval: 10s
      timeout: 10s
      retries: 5
  worker:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    container_name: forex_worker
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

volumes:
  pgdata:
    driver: local
    name: pgdata
  redisdata:
    driver: local
    name: redisdata
