version: '3.8'

services:
  api:
    image: forex:production
    restart: always
    command: sh scripts/start_api.sh
    environment:
      - DJANGO_ENV=production
      - DJANGO_PORT=${DJANGO_PORT}
  cache:
    restart: always
    environment:
      - REDIS_PORT=${REDIS_PORT}
  db:
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
  worker:
    image: worker:production
    restart: always
    command: sh scripts/start_worker.sh
    environment:
      - DJANGO_ENV=production
